/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNews"];
        put?: never;
        post: operations["createNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["newsAnalyses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyzeNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHypotheses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hypotheses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHypothesis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModelRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/model-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/model-profiles/{profile}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hypotheses/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transitionHypothesis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hypotheses/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHypothesisTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hypotheses/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hypotheses/{id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPrediction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDuePredictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/{id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyPrediction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ClaimType: "FACT" | "INFERENCE" | "HYPOTHESIS" | "PREDICTION" | "UNKNOWN";
        /** @enum {string} */
        DomainType: "TECH" | "AI" | "BUSINESS" | "FINANCE" | "MACRO" | "POLICY" | "GEOPOLITICS" | "REAL_ESTATE" | "ENERGY" | "CONSUMER" | "HEALTHCARE" | "EMPLOYMENT" | "OTHER";
        /** @enum {string} */
        NewsGrade: "C" | "B" | "A" | "S";
        /** @enum {string} */
        JobStatus: "QUEUED" | "NORMALIZING" | "EXTRACTING_FACTS" | "ANALYZING" | "GENERATING_HYPOTHESES" | "VERIFYING" | "SYNTHESIZING" | "COMPLETED" | "FAILED";
        /** @enum {string} */
        ModelPurpose: "FAST_ANALYSIS" | "DEEP_ANALYSIS" | "FACT_EXTRACTION" | "CLASSIFICATION" | "COUNTER_ARGUMENT" | "SYNTHESIS";
        SourceRef: {
            /** Format: uuid */
            sourceId: string;
            quote: string;
            startOffset: number;
            endOffset: number;
        };
        Statement: {
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            factRefs?: string[];
            derivedFromRefs?: string[];
            /** Format: uuid */
            targetHypothesisRef?: string | null;
            /** Format: uuid */
            rivalsHypothesisRef?: string | null;
        };
        Fact: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            /** @enum {string|null} */
            verificationStatus?: "REPORTED" | "CORROBORATED" | "DISPUTED" | null;
        };
        Variable: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            direction: "UP" | "DOWN" | "UNCHANGED" | "UNKNOWN";
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            previousState?: string | null;
            currentState?: string | null;
            magnitude?: string | null;
            whyItMatters?: string | null;
            factRefs?: string[];
        };
        CausalLink: {
            /** Format: uuid */
            id: string;
            cause: string;
            effect: string;
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            /** @enum {string|null} */
            supportLevel?: "SUPPORTED" | "PLAUSIBLE" | "SPECULATIVE" | null;
            factRefs?: string[];
        };
        StakeholderImpact: {
            /** Format: uuid */
            id: string;
            stakeholder: string;
            /** @enum {string} */
            direction: "BENEFITS" | "HARMED" | "MIXED" | "UNKNOWN";
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            factRefs?: string[];
        };
        Hypothesis: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            status: components["schemas"]["HypothesisStatus"];
            confidenceReason: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            supportingFactRefs?: string[];
            supportingEvidenceRefs?: string[];
            contradictingEvidenceRefs?: string[];
            assumptions?: string[];
            alternativeHypothesisRefs?: string[];
            falsificationConditions?: components["schemas"]["Statement"][];
            confidenceBand?: components["schemas"]["ConfidenceBand"];
        };
        Evidence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            hypothesisId: string;
            /** @enum {string} */
            stance: "SUPPORTS" | "CONTRADICTS" | "NEUTRAL";
            strength: number;
            /** Format: uuid */
            sourceId: string;
            reason: string;
            /** Format: date-time */
            createdAt: string;
            factRefs?: string[];
            /** Format: uuid */
            analysisId?: string | null;
        };
        Prediction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            hypothesisId: string;
            statement: string;
            /** @enum {string} */
            type: "PREDICTION";
            /** Format: date-time */
            expectedBy: string;
            /** @enum {string} */
            status: "OPEN" | "CONFIRMED" | "REJECTED" | "PARTIAL" | "UNRESOLVED";
            verificationCriteria: string;
            observable?: string | null;
            whereToCheck?: string | null;
            basisFactRefs?: string[];
        };
        Indicator: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            predictionId: string | null;
            name: string;
            measurement: string;
            frequency: string;
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            whereToCheck?: string | null;
            supportingResult?: string | null;
            contradictingResult?: string | null;
            /** @enum {string|null} */
            priority?: "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN" | null;
            /** Format: date-time */
            deadline?: string | null;
            /** Format: uuid */
            hypothesisRef?: string | null;
        };
        ConfidenceAssessment: {
            score: number;
            reason: string;
            /** @enum {boolean} */
            isProbability: false;
            band?: components["schemas"]["ConfidenceBand"];
            method?: components["schemas"]["ConfidenceMethod"];
            rubricVersion?: string | null;
            dimensions?: components["schemas"]["ConfidenceDimension"][];
            advisoryScore?: number | null;
        };
        AnalysisResult: {
            summary: string;
            facts: components["schemas"]["Fact"][];
            variables: components["schemas"]["Variable"][];
            mechanisms: components["schemas"]["CausalLink"][];
            stakeholders: components["schemas"]["StakeholderImpact"][];
            firstOrderEffects: components["schemas"]["Statement"][];
            secondOrderEffects: components["schemas"]["Statement"][];
            hypotheses: components["schemas"]["Hypothesis"][];
            alternativeExplanations: components["schemas"]["Statement"][];
            counterArguments: components["schemas"]["Statement"][];
            falsificationConditions: components["schemas"]["Statement"][];
            corroboratingSignals: components["schemas"]["CorroboratingSignal"][];
            verificationIndicators: components["schemas"]["Indicator"][];
            unknowns: components["schemas"]["Statement"][];
            confidenceAssessment: components["schemas"]["ConfidenceAssessment"];
            upcomingObservations: components["schemas"]["Statement"][];
            modifiesExistingHypotheses: boolean;
            demo: boolean;
            sourceAssessment?: components["schemas"]["SourceAssessment"];
            predictions?: components["schemas"]["Prediction"][];
            protocolVersion?: string | null;
            provenance?: components["schemas"]["Provenance"];
        };
        Source: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string | null;
            text: string;
            /** @enum {string} */
            extractionStatus: "PASTED" | "EXTRACTED" | "NEEDS_TEXT";
            message: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description At least one nonblank URL or text is required. URL must use HTTP(S). */
        NewsInput: {
            /** Format: uri */
            url?: string | null;
            text?: string | null;
            title?: string | null;
        };
        NewsItem: {
            /** Format: uuid */
            id: string;
            title: string;
            source: components["schemas"]["Source"];
            domain: components["schemas"]["DomainType"];
            /** Format: date-time */
            createdAt: string;
        };
        NewsValueScore: {
            grade: components["schemas"]["NewsGrade"];
            importance: number;
            relevance: number;
            novelty: number;
            variableImpact: number;
            verifiability: number;
            reason: string;
        };
        Analysis: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            newsId: string;
            /** Format: uuid */
            jobId: string;
            domain: components["schemas"]["DomainType"];
            score: components["schemas"]["NewsValueScore"];
            result: components["schemas"]["AnalysisResult"];
            /** Format: date-time */
            createdAt: string;
        };
        JobEvent: {
            /** Format: int64 */
            sequence: number;
            status: components["schemas"]["JobStatus"];
            step: string;
            message: string;
            /** Format: date-time */
            at: string;
        };
        AnalysisJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            newsId: string;
            status: components["schemas"]["JobStatus"];
            /** Format: uuid */
            analysisId: string | null;
            error: string | null;
            correlationId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            events: components["schemas"]["JobEvent"][];
        };
        Topic: {
            /** Format: uuid */
            id: string;
            name: string;
            newsIds: string[];
            hypothesisIds: string[];
        };
        HypothesisEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            hypothesisId: string;
            /** @enum {string} */
            eventType: "CREATED" | "EVIDENCE_ADDED" | "CONFIDENCE_CHANGED" | "PREDICTION_VERIFIED" | "STATUS_CHANGED";
            previousConfidence: number | null;
            confidence: number;
            reason: string;
            /** Format: date-time */
            createdAt: string;
            previousStatus?: components["schemas"]["HypothesisStatus"];
            status?: components["schemas"]["HypothesisStatus"];
        };
        HypothesisDetail: {
            hypothesis: components["schemas"]["Hypothesis"];
            timeline: components["schemas"]["HypothesisEvent"][];
            evidence: components["schemas"]["Evidence"][];
            predictions: components["schemas"]["Prediction"][];
            /** Format: int64 */
            version: number;
        };
        ModelProfile: {
            provider: string;
            model: string;
            baseUrl: string;
            apiKeyEnv: string;
            temperature: number;
            maxTokens: number;
            timeout: number;
            structuredOutput: boolean;
            toolCalling: boolean;
            enabled: boolean;
        };
        NamedModelProfile: {
            name: string;
            profile: components["schemas"]["ModelProfile"];
            /** @enum {string} */
            effectiveMode: "MOCK" | "LIVE" | "DISABLED";
        };
        ModelRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            provider: string;
            model: string;
            purpose: components["schemas"]["ModelPurpose"];
            promptVersion: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            /** Format: int64 */
            latencyMs: number;
            /** Format: int64 */
            inputTokens: number | null;
            /** Format: int64 */
            outputTokens: number | null;
            /** Format: int64 */
            totalTokens: number | null;
            estimatedCost: number | null;
            /** @enum {string} */
            status: "SUCCEEDED" | "FAILED";
            errorType: string | null;
            correlationId: string;
        };
        ApiError: {
            code: string;
            message: string;
            requestId: string;
        };
        SourceAssessment: {
            /** @enum {string} */
            sourceType: "PRIMARY_DOCUMENT" | "OFFICIAL_STATEMENT" | "COMPANY_DISCLOSURE" | "PRESS_RELEASE" | "NEWS_REPORT" | "WIRE_REPUBLICATION" | "OPINION_ANALYSIS" | "SOCIAL_POST" | "UNKNOWN";
            publisher: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            /** @enum {string} */
            primaryOrSecondary: "PRIMARY" | "SECONDARY" | "UNKNOWN";
            /** @enum {string} */
            independence: "SINGLE_SOURCE" | "SAME_PUBLISHER_DUPLICATE" | "INDEPENDENT_SET" | "UNKNOWN";
            independenceKey?: string | null;
            /** @enum {string} */
            contentCompleteness: "COMPLETE" | "PARTIAL" | "TRUNCATED" | "METADATA_ONLY" | "UNKNOWN";
            notes: string[];
        };
        /** @enum {string} */
        ConfidenceBand: "VERY_LOW" | "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH";
        /** @enum {string} */
        ConfidenceMethod: "MODEL_JUDGMENT" | "RUBRIC";
        /** @enum {string} */
        HypothesisStatus: "OPEN" | "STRENGTHENING" | "WEAKENING" | "CONFIRMED" | "REJECTED" | "UNRESOLVED" | "SUPPORTED" | "CHALLENGED" | "ARCHIVED";
        ConfidenceDimension: {
            /** @enum {string} */
            dimension: "D1_SOURCE_QUALITY" | "D2_EVIDENCE_DIRECTNESS" | "D3_INDEPENDENT_CORROBORATION" | "D4_MECHANISM_SUPPORT" | "D5_COUNTER_EVIDENCE_RESILIENCE";
            level: number;
            points: number;
            note?: string | null;
        };
        CorroboratingSignal: {
            type: components["schemas"]["ClaimType"];
            statement: string;
            reasoning: string;
            confidence: number;
            sourceRefs: components["schemas"]["SourceRef"][];
            /** Format: uuid */
            hypothesisRef: string;
            whereToCheck: string;
            window?: string | null;
            /** @enum {string} */
            status: "NOT_OBSERVED" | "OBSERVED" | "NOT_FOUND";
        };
        Provenance: {
            protocolVersion?: string | null;
            domainStrategyId?: string | null;
            rubricVersion?: string | null;
            promptVersions?: string[];
            modelRunIds?: string[];
        };
        /** @enum {string} */
        HypothesisTransitionCause: "EVIDENCE_ADDED" | "EVIDENCE_CHANGED" | "PREDICTION_VERIFIED" | "FALSIFICATION_OBSERVED" | "DEADLINE_PASSED";
        /** @enum {string} */
        VerificationOutcome: "CONFIRMED" | "PARTIAL" | "REJECTED" | "UNRESOLVED";
        HypothesisTransitionCommand: {
            /** Format: uuid */
            operationId: string;
            /** Format: int64 */
            expectedVersion: number;
            cause: components["schemas"]["HypothesisTransitionCause"];
            reason: string;
            /** Format: uuid */
            evidenceRef?: string | null;
            /** Format: uuid */
            predictionRef?: string | null;
            verificationOutcome?: components["schemas"]["VerificationOutcome"];
        };
        HypothesisTransitionResult: {
            /** Format: uuid */
            operationId: string;
            /** Format: uuid */
            hypothesisId: string;
            applied: boolean;
            /** Format: int64 */
            previousVersion: number;
            /** Format: int64 */
            version: number;
            previousStatus: components["schemas"]["HypothesisStatus"];
            status: components["schemas"]["HypothesisStatus"];
            previousConfidence: number;
            confidence: number;
            confidenceBand?: components["schemas"]["ConfidenceBand"];
            rubricVersion?: string | null;
            /** Format: uuid */
            eventId: string;
            /** Format: date-time */
            occurredAt: string;
        };
        HypothesisTimeline: {
            /** Format: uuid */
            hypothesisId: string;
            /** Format: int64 */
            version: number;
            status: components["schemas"]["HypothesisStatus"];
            confidence: number;
            items: components["schemas"]["HypothesisEvent"][];
        };
        EvidenceCreateRequest: {
            /** Format: uuid */
            sourceId: string;
            /** @enum {string} */
            stance: "SUPPORTS" | "CONTRADICTS" | "NEUTRAL";
            strength: number;
            reason: string;
            factRefs?: string[];
            /** Format: uuid */
            analysisId?: string | null;
        };
        PredictionCreateRequest: {
            statement: string;
            observable: string;
            /** Format: date-time */
            expectedBy: string;
            verificationCriteria: string;
            whereToCheck: string;
            basisFactRefs?: string[];
        };
        PredictionVerificationCommand: {
            /** Format: uuid */
            operationId: string;
            result: components["schemas"]["VerificationOutcome"];
            reason: string;
            /** Format: uuid */
            evidenceRef?: string | null;
            /** Format: date-time */
            verifiedAt?: string | null;
        };
        PredictionVerificationResult: {
            prediction: components["schemas"]["Prediction"];
            applied: boolean;
            /** Format: uuid */
            verificationId: string;
            hypothesisTransition: components["schemas"]["HypothesisTransitionResult"];
        };
        DuePredictions: {
            /** Format: date-time */
            asOf: string;
            predictions: components["schemas"]["Prediction"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"][];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsInput"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    newsAnalyses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"][];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    analyzeNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    jobEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example id: 1
                     *     event: progress
                     *     data: {"status":"QUEUED"}
                     */
                    "text/event-stream": string;
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listHypotheses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hypothesis"][];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getHypothesis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisDetail"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"][];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listModelRuns: {
        parameters: {
            query?: {
                jobId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRun"][];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedModelProfile"][];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProfile"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedModelProfile"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    transitionHypothesis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HypothesisTransitionCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisTransitionResult"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getHypothesisTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisTimeline"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceCreateRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createPrediction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionCreateRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prediction"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listDuePredictions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuePredictions"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    verifyPrediction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionVerificationCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionVerificationResult"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
